### PR TITLE
Add runtime support

### PR DESCRIPTION
**Pull request by Fymyte**
#48
Signed-off-by: Fymyte <pierguill@gmail.com>

### CODE REVIEW

**Comment by Fymyte** [comment]
I am not sure of how we should handle filenames with wildcard,

**Comment by vigoux** [comment]
Maybe allow wildcards in filenames ? That would make is simpler...

**Comment by Fymyte** [comment]
After some test, it seems to be correct to have wildcard even where a single file is expected.

But it raise another issue: `:h filename` says that if a single file is expected, whitespaces inside filename is authorized, but if there is more than one, spaces has to be escaped.

**Comment by vigoux** [comment]
This constraint makes it barely possible to correctly parse them, without any semantics (which is the problem with most parts of VimL actually).
Thus, I would suggest we do a best effort, and when an _unescape_ whitespace is encountered, this is considered the end of this path.

I expect people to actually be careful about what they are writing, and tbf, I am pretty sure vim itself does not know how to parse those cases in the `syntax` files (as this is actually not possible in the general case).

**Review by vigoux — APPROVED** [review]

**Pull request merged**
