### PR TITLE
Fix parsing error for functions defined with bangs

### LINKED ISSUE #105: Parsing errors in the most recent version
Mistakenly reported on nvim-treesitter repo https://github.com/nvim-treesitter/nvim-treesitter/issues/3040

In between 26bc9a27b9f750544f4388d453e00c28fea1b540 and 7abbe04ba9e2d1f321703a8fbad39828fa8bcf7d the parser stopped working on the following file:

```vim
function! Fn_1() abort
endfunction

function! s:fn_2() abort
endfunction
```

The TSPlayground output went from

Before:
```
function_definition [0, 0] - [1, 11]
  bang [0, 8] - [0, 9]
  function_declaration [0, 10] - [0, 16]
    name: identifier [0, 10] - [0, 14]
    parameters: parameters [0, 14] - [0, 16]
function_definition [3, 0] - [4, 11]
  bang [3, 8] - [3, 9]
  function_declaration [3, 10] - [3, 18]
    name: scoped_identifier [3, 10] - [3, 16]
      scope [3, 10] - [3, 12]
      identifier [3, 12] - [3, 16]
    parameters: parameters [3, 16] - [3, 18]
```

After:
```
ERROR [0, 0] - [0, 22]
  unary_operation [0, 8] - [0, 16]
    call_expression [0, 10] - [0, 16]
      function: identifier [0, 10] - [0, 14]
  keyword [0, 17] - [0, 22]
unknown_builtin_statement [1, 0] - [1, 11]
  unknown_command_name [1, 0] - [1, 11]
ERROR [3, 0] - [3, 24]
  unary_operation [3, 8] - [3, 18]
    call_expression [3, 10] - [3, 18]
      function: scoped_identifier [3, 10] - [3, 16]
        scope [3, 10] - [3, 12]
        identifier [3, 12] - [3, 16]
  keyword [3, 19] - [3, 24]
unknown_builtin_statement [4, 0] - [4, 11]
  unknown_command_name [4, 0] - [4, 11]
```

### PR DESCRIPTION
**Pull request by jchros**
Closes #105 (from which I added some test cases).

### CODE REVIEW

**Comment by jchros** [comment]
In commit ade2eed I noted that bangs should be put right after the name of the command; Vim's help files mention this in [`:help :_!`](https://vimhelp.org/cmdline.txt.html#%3A_%21).

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
Could you add a reference to this help page in a comment above the `bang` definition?
This way it will be easier to remember why this decision was done.

**Comment by jchros** [comment]
I have rebased `fix-func-bang` with the changes from 7e8ad59f3c3aa1dcaf1c948b01013a15e3495aa0..4e1f656a69310a1603b78089f8ce83d33801a4b5.

Side note: I see that these commits revert the `lockfileVersion` to 1 in `package-lock.json`.  Is that intentional?

**Comment by vigoux** [comment]
> Side note: I see that these commits revert the `lockfileVersion` to 1 in `package-lock.json`. Is that intentional?

I don't think so, I'll fix that later.

**Pull request merged**
