### PR TITLE
Add support for optional function arguments

### LINKED ISSUE #54: Add support for optional function arguments
VimL has optional function arguments, but the current grammar doesn't seem to support it.

See `:h optional-function-argument` for details.

tl;dr:

```viml
  function Something(key, value = 10)
     echo a:key .. ": " .. a:value
  endfunction
  call Something('empty')	"empty: 10"
  call Something('key', 20)	"key: 20"
```

### PR DESCRIPTION
**Pull request by reegnz**
VimL supports optional function arguments.

This change doesn't care much about the valid order of arguments, it
just enumerates the possible arguments.

See `h: optional-function-arguments` in vim for docs on the language
construct.

Fixes  #54

### CODE REVIEW

**Comment by reegnz** [comment]
I could not run `tree-sitter generate` with the `--abi=latest` flag, it won't accept it. The parser changes do seem to work for me with ABI=13 though.

**Comment by Fymyte** [comment]
> I could not run `tree-sitter generate` with the `--abi=latest` flag, it won't accept it. The parser changes do seem to work for me with ABI=13 though.

In order to use the latest version of treesitter, you can
- on archlinux, tree-sitter-git in the AUR provides the latest version of tree-sitter
- build from source:
```sh
git clone https://github.com/tree-sitter/tree-sitter
cd tree-sitter
cargo install --path cli
make
sudo make install
```
the latest cli should be located in target/release/tree-sitter

**Comment by Fymyte** [comment]
I have tested the pr locally with the latest ABI version and works nicely ! 👍

**Review by vigoux — APPROVED** [review]

**Comment by vigoux** [comment]
I'll regenerate the parser and all, but it all seems great !

**Comment by reegnz** [comment]
Thanks @vigoux !

**Comment by reegnz** [comment]
@vigoux this is interesting, it seems like it doesn't work for me with the latest ABI, only with 13...
I'm using the latest release of tree-sitter (0.20.2).

**Pull request merged**
